version: '3.8'

services:
  apache:
    build: ./docker
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mariadb
    networks:
      - webasyst_network
    environment:
      - WAIT_HOSTS=mariadb:3306
    platform: ${DOCKER_DEFAULT_PLATFORM}  # или linux/arm64, если нужно строго под ARM

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: webasyst
      MARIADB_USER: webasyst
      MARIADB_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - webasyst_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - webasyst_network
    platform: linux/amd64

volumes:
  db_data:

networks:
  webasyst_network:
    driver: bridge
