version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"   # Web UI
      - "443:443"
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - webasyst_network

  apache:
    build: ./docker
    container_name: apache
    volumes:
      - ./src:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mariadb
    environment:
      - WAIT_HOSTS=mariadb:3306
    networks:
      - webasyst_network
    labels:
      - "traefik.enable=false"
    expose:
      - "80"  # не пробрасываем наружу — проксируем через NPM

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: webasyst
      MARIADB_USER: webasyst
      MARIADB_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webasyst_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - webasyst_network
    expose:
      - "80"  # тоже только через NPM

volumes:
  db_data:

networks:
  webasyst_network:
    driver: bridge
